name: xgrep
version: 0.0.3
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/xgrep
description: >
  A library/script for locating/grepping things on linux
dependencies:

# custom <xgrep dependencies>

  id: "^1.0.4"
    
  ebisu: "^0.0.14"
    
  mongo_dart: "^0.1.46"

  collection: "^1.1.0"

# end <xgrep dependencies>

dev_dependencies:
  yaml: "any"
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <xgrep dev dependencies>


# end <xgrep dev dependencies>

dependency_overrides:
# custom <xgrep dependency overrides>
    
# end <xgrep dependency overrides>

transformers:

# custom <xgrep transformers>

environment:
  sdk: ">=1.8.0 <2.0.0"

# end <xgrep transformers>

