name: xgrep
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <xgrep dependencies>

  id:
    git: git://github.com/patefacio/id
    
  ebisu:
    git: git://github.com/patefacio/ebisu
    
  mongo_dart:
    git: git://github.com/vadimtsushko/mongo_dart

  args: "^0.13.0"

# end <xgrep dependencies>

dev_dependencies:
  yaml: "any"
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <xgrep dev dependencies>


# end <xgrep dev dependencies>

dependency_overrides:
# custom <xgrep dependency overrides>

  quiver: '^0.21.1'
  id:
    git: git://github.com/patefacio/id
    
#  ebisu:
#    path: /home/dbdavidson/dev/open_source/ebisu
#    git: git://github.com/patefacio/ebisu

  hop: ">=0.29.0"
  args: "^0.13.0"
  dart_style: "^0.1.6"
    
# end <xgrep dependency overrides>

transformers:

# custom <xgrep transformers>
# end <xgrep transformers>

