name: xgrep
version: 0.0.6
author: Daniel Davidson <dbdavidson@yahoo.com>
homepage: https://github.com/patefacio/xgrep
description: >
  A library/script for locating/grepping things on linux
dependencies:

# custom <xgrep dependencies>

  id: "^1.0.10"
    
  ebisu: "^0.6.2"
    
  mongo_dart: "^0.1.47"

  collection: "^1.1.1"


# end <xgrep dependencies>

dev_dependencies:
  yaml: "any"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <xgrep dev dependencies>

  test: "^0.12.0"

# end <xgrep dev dependencies>

dependency_overrides:
# custom <xgrep dependency overrides>

#  ebisu:
#    path: /home/dbdavidson/dev/open_source/ebisu

environment:
  sdk: ">=1.8.0 <2.0.0"
    
# end <xgrep dependency overrides>

transformers:

# custom <xgrep transformers>
# end <xgrep transformers>

